import styles from '../styles/Home.module.css';
import Head from 'next/head';
import { ConnectButton } from '@rainbow-me/rainbowkit';


function SearchContent() {
    return (
        <div className={styles.container}>
          <Head>
            <title>VerifiedChain</title>
            <meta
              name="description"
              content="Generated by @rainbow-me/create-rainbowkit"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
          {/*   <ConnectButton /> */}
    
            <h1 className={styles.title}>
              Welcome to <a href="">VerifiedChain</a> 
            </h1>
            <div className={styles.search}>
              <input type="search" placeholder="Search Here" 
              className='searching'/>
              <button>search</button>
            </div>
    
    
            <div className={styles.grid}>
              <h2>Top 10 best the last week </h2>
              <div className={styles.rectangle}>
                <p>1</p>
                <p>98 Submissions verified</p>
                <p>3 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>2</p>
                <p>86 Submissions verified</p>
                <p>5 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>3</p>
                <p>75 Submissions verified</p>
                <p>7 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>4</p>
                <p>55 Submissions verified</p>
                <p>15 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>5</p>
                <p>70 Submissions verified</p>
                <p>7 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>6</p>
                <p>65 Submissions verified</p>
                <p>7 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>7</p>
                <p>64 Submissions verified</p>
                <p>7 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>8</p>
                <p>62 Submissions verified</p>
                <p>9 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>9</p>
                <p>60Submissions verified</p>
                <p>11 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
              <div className={styles.rectangle}>
                <p>10</p>
                <p>59 Submissions verified</p>
                <p>11 Submissions rejected</p>
                <p>0x8Ba...f518</p>
              </div>
    
            </div>
          </main>
    
          <footer className={styles.footer}>
            <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
              Made with ❤️ by your frens at 🌈
            </a>
          </footer>
        </div>
      );
}

export default SearchContent;