import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from "next/router";
import { useAccount } from "wagmi";
import Image from "next/image";
import { useEffect } from 'react';
import VerityText from '../components/verify';
import React from 'react';


const Home: NextPage = () => {

  const { isConnected } = useAccount();
  const router = useRouter();

  console.log(isConnected);

  // ***
  // Uncomment this code to redirect after login with the wallet.
  // ****
  //
  /*  useEffect(() => {
     if(isConnected)
      router.push('/page-to-redirect')
     }
   },[isConnected]); */

  return (
    <div className={styles.container}>
      <Head>
        <title>VerifiedChain</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={styles.main}>
        <header style={{ width: '100%', height: '60px',justifyContent: 'space-between' }}>
          <div style={{ float: 'left' }}>
           <img src='../assets/logo.png' alt="logo" sizes=""/>
          </div>
          <div style={{ float: 'right' }}>
            <ConnectButton />
          </div>
        </header>
        <main style={{ width: '90%', margin: '0 auto', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
      {isConnected ? <VerityText /> : null}
    </main>
      </body>
    </div>
  );
};

export default Home;
