import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import { useRouter } from "next/router";
import { useAccount } from "wagmi";
import { useEffect } from 'react';
import VerityText from '../components/verify';



const Home: NextPage = () => {

  const { isConnected } = useAccount();
  const router = useRouter();
  
  console.log(isConnected);
  
  // ***
  // Uncomment this code to redirect after login with the wallet.
  // ****
  //
  /*  useEffect(() => {
     if(isConnected)
      router.push('/page-to-redirect')
     }
   },[isConnected]); */

  return (
    <div className={styles.container}>
         <Head>
            <title>VerifiedChain</title>
            <meta
              name="description"
              content="Generated by @rainbow-me/create-rainbowkit"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <ConnectButton /> {isConnected ? <VerityText/> : null } 
          </main>
    </div>
  );
};

export default Home;
